global:
  resolve_timeout: 5m
route:
  group_by: ['alertname', 'cluster', 'instance']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 5m
  receiver: 'webhook'

receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://152.32.151.73:9094/prometheusalert?type=fs&tpl=prometheus-fs&fsurl=https://open.feishu.cn/open-apis/bot/v2/hook/861ecf9c-b7c3-41e5-bf30-241313041c79'