services:
  node-exporter:
    image: prom/node-exporter:v1.3.1
    restart: unless-stopped
    hostname: node-exporter
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'